# Generated by Django 3.2.11 on 2022-04-07 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('updates', '0002_auto_20220407_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='featured_image',
            field=models.URLField(blank=True, max_length=1024, null=True, verbose_name='image'),
        ),
    ]
