# Generated by Django 3.2 on 2022-01-23 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_ticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
