# Generated by Django 3.2.11 on 2022-04-02 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_delete_ticket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='has_sizes',
        ),
    ]
